window.TOOLS = [
  {
    id:"bosch-gbh",
    name:"Перфоратор FORTE RH 26",
    cat:"Электроинструмент",
    brand:"FORTE",
    priceDay:590,
    price3:1490,
    priceWeek:2790,
    priceMonth:7990,
    buyPrice:15990,
    icon:"🔨",
    stock:true,
    popular:true,
    desc:"Профессиональный перфоратор FORTE для сверления бетона, кирпича и камня. 3 режима работы.",
    specs:{"Мощность":"800 Вт", "Энергия":"2.7 Дж", "Вес":"2.7 кг", "Патрон":"SDS-Plus"}
  },
  {
    id:"makita-drill",
    name:"Дрель-шуруповерт FORTE DS 18",
    cat:"Электроинструмент",
    brand:"FORTE",
    priceDay:450,
    price3:1150,
    priceWeek:1990,
    priceMonth:5490,
    buyPrice:12990,
    icon:"🪛",
    stock:true,
    popular:true,
    desc:"Бесщеточный шуруповерт FORTE 18V. Для сборки мебели и монтажа.",
    specs:{"Крутящий":"50 Нм", "Обороты":"0-1900", "Аккум":"2x 3.0Ач", "Вес":"1.8 кг"}
  },
  {
    id:"dewalt-grinder",
    name:"Болгарка FORTE AG 125",
    cat:"Электроинструмент",
    brand:"FORTE",
    priceDay:520,
    price3:1290,
    priceWeek:2290,
    priceMonth:6490,
    buyPrice:8990,
    icon:"⚙️",
    stock:true,
    popular:true,
    desc:"УШМ FORTE 125мм с защитой от заклинивания и плавным пуском. Для резки металла и плитки.",
    specs:{"Мощность":"1500 Вт", "Диск":"125 мм", "Обороты":"2800-11000", "Вес":"2.4 кг"}
  },
  {
    id:"husqvarna-mower",
    name:"Газонокосилка FORTE LM 40",
    cat:"Садовая техника",
    brand:"FORTE",
    priceDay:990,
    price3:2590,
    priceWeek:4490,
    priceMonth:11990,
    buyPrice:32990,
    icon:"🌿",
    stock:true,
    popular:true,
    desc:"Бензиновая газонокосилка FORTE для участков до 1000м². Травосборник 50л.",
    specs:{"Мощность":"2.8 л.с.", "Ширина":"40 см", "Травосборник":"50 л", "Вес":"24 кг"}
  },
  {
    id:"karcher-k5",
    name:"Мойка FORTE HPW 145",
    cat:"Клининг",
    brand:"FORTE",
    priceDay:850,
    price3:2190,
    priceWeek:3790,
    priceMonth:9990,
    buyPrice:27990,
    icon:"💦",
    stock:true,
    popular:true,
    desc:"Мойка высокого давления FORTE 145 бар. Для авто, фасадов, дорожек.",
    specs:{"Давление":"145 бар", "Расход":"500 л/ч", "Мощность":"2.1 кВт", "Шланг":"8 м"}
  },
  {
    id:"resanta-weld",
    name:"Сварочный инвертор FORTE MMA-190",
    cat:"Сварочное",
    brand:"FORTE",
    priceDay:650,
    price3:1690,
    priceWeek:2890,
    priceMonth:7490,
    buyPrice:11990,
    icon:"🔥",
    stock:true,
    popular:false,
    desc:"Инвертор FORTE MMA 190А, варит электродом до 5мм. Для дачи и гаража.",
    specs:{"Ток":"10-190 А", "Электрод":"1.6-5 мм", "ПВ":"70%", "Вес":"4.5 кг"}
  },
  {
    id:"flir-thermal",
    name:"Тепловизор Flir C5",
    cat:"Измерительное",
    brand:"Flir",
    priceDay:1490,
    price3:3890,
    priceWeek:6490,
    priceMonth:16990,
    buyPrice:74990,
    icon:"🌡️",
    stock:true,
    popular:true,
    desc:"Компактный тепловизор для поиска теплопотерь и проверки электрики.",
    specs:{"Разрешение":"160x120", "Диапазон":"-20..400°C", "Wi-Fi":"Да", "Вес":"0.19 кг"}
  },
  {
    id:"bosch-level",
    name:"Лазерный уровень Bosch GCL 2-50",
    cat:"Измерительное",
    brand:"Bosch",
    priceDay:490,
    price3:1190,
    priceWeek:1990,
    priceMonth:5490,
    buyPrice:13990,
    icon:"📐",
    stock:true,
    popular:false,
    desc:"Комбинированный лазер: 2 линии + 2 точки. Дальность 20м.",
    specs:{"Дальность":"20 м", "Точность":"±0.3 мм/м", "Лазер":"2x линия", "Батарея":"4x AA"}
  },
  {
    id:"concrete-mixer",
    name:"Бетономешалка FORTE 130л",
    cat:"Строительное",
    brand:"FORTE",
    priceDay:790,
    price3:1990,
    priceWeek:3490,
    priceMonth:8990,
    buyPrice:18990,
    icon:"🏗️",
    stock:true,
    popular:false,
    desc:"Гравитационная бетономешалка FORTE 130л, венец чугунный. Для фундамента и стяжки.",
    specs:{"Объем":"130 л", "Мощность":"550 Вт", "Венец":"чугун", "Вес":"51 кг"}
  },
  {
    id:"makita-jack",
    name:"Отбойный молоток FORTE RH 50",
    cat:"Строительное",
    brand:"FORTE",
    priceDay:1190,
    price3:2990,
    priceWeek:5290,
    priceMonth:13990,
    buyPrice:45990,
    icon:"💥",
    stock:true,
    popular:false,
    desc:"Мощный отбойник FORTE 19.1 Дж для демонтажа бетона и асфальта.",
    specs:{"Энергия":"19.1 Дж", "Мощность":"1510 Вт", "Патрон":"SDS-Max", "Вес":"9.7 кг"}
  },
  {
    id:"stihl-trimmer",
    name:"Триммер FORTE BC 33",
    cat:"Садовая техника",
    brand:"FORTE",
    priceDay:690,
    price3:1790,
    priceWeek:2990,
    priceMonth:7990,
    buyPrice:19990,
    icon:"🌾",
    stock:true,
    popular:false,
    desc:"Бензокоса FORTE для травы и бурьяна. Леска + нож в комплекте.",
    specs:{"Мощность":"1.0 л.с.", "Режущий":"леска/нож", "Вес":"5 кг", "Бак":"0.33 л"}
  },
  {
    id:"generator-3kw",
    name:"Генератор FORTE FG 3000 3кВт",
    cat:"Строительное",
    brand:"FORTE",
    priceDay:890,
    price3:2290,
    priceWeek:3990,
    priceMonth:9990,
    buyPrice:24990,
    icon:"⚡",
    stock:true,
    popular:false,
    desc:"Бензиновый генератор FORTE 3кВт для стройки и резервного питания.",
    specs:{"Мощность":"3 кВт", "Бак":"15 л", "Запуск":"ручной", "Вес":"44 кг"}
  },
  {
    id:"karcher-vac",
    name:"Строительный пылесос FORTE VC 30",
    cat:"Клининг",
    brand:"FORTE",
    priceDay:750,
    price3:1890,
    priceWeek:3290,
    priceMonth:8490,
    buyPrice:21990,
    icon:"🧹",
    stock:true,
    popular:false,
    desc:"Пылесос FORTE для сухой и влажной уборки, 30л бак, розетка для инструмента.",
    specs:{"Объем":"30 л", "Мощность":"1300 Вт", "Розетка":"Да", "Вес":"9.5 кг"}
  },
  {
    id:"ladder-trans",
    name:"Лестница-трансформер FORTE 4x4",
    cat:"Строительное",
    brand:"FORTE",
    priceDay:590,
    price3:1490,
    priceWeek:2490,
    priceMonth:6490,
    buyPrice:15990,
    icon:"🪜",
    stock:true,
    popular:false,
    desc:"Алюминиевая трансформер FORTE 4 секции по 4 ступени. До 5.8м.",
    specs:{"Высота":"5.8 м", "Секции":"4x4", "Материал":"алюминий", "Вес":"14 кг"}
  },
  {
    id:"vibro-plate",
    name:"Виброплита FORTE VP 90",
    cat:"Строительное",
    brand:"FORTE",
    priceDay:1390,
    price3:3590,
    priceWeek:5990,
    priceMonth:14990,
    buyPrice:39990,
    icon:"🧱",
    stock:true,
    popular:false,
    desc:"Виброплита FORTE 90кг для трамбовки песка, щебня, плитки.",
    specs:{"Вес":"90 кг", "Сила":"15 кН", "Глубина":"30 см", "Двигатель":"бензин"}
  },
  {
    id:"bosch-jigsaw",
    name:"Лобзик FORTE JS 800",
    cat:"Электроинструмент",
    brand:"FORTE",
    priceDay:390,
    price3:990,
    priceWeek:1690,
    priceMonth:4490,
    buyPrice:8990,
    icon:"🪚",
    stock:true,
    popular:false,
    desc:"Электролобзик FORTE для фигурного реза дерева и металла.",
    specs:{"Мощность":"710 Вт", "Пропил":"80 мм", "Ход":"20 мм", "Вес":"2.5 кг"}
  }
];

window.CATS = ["Все","Электроинструмент","Садовая техника","Сварочное","Измерительное","Клининг","Строительное"];
